### ISSUE TITLE
Remove unwanted files for GitHub

### ISSUE THREAD

**Issue by AlexandruIliescu** [Denisa1128/Event-Management_System#10]
Please consider removing files that should not be visible for Github, files like the ones from below:
- .mvn/*
- mvw file
- mvnw.cmd

Also, please consider adding a readme file that explains the tech stack you are using, the name of the project and other relevant details for visibility.

<img width="919" alt="image" src="https://github.com/user-attachments/assets/4adb5541-a7e5-4272-bcca-bbc78b38f528">

**Comment by alinaitschool** [comment]
@AlexandruIliescu why should remove this?
 Should not be delete it since this these files and directories are part of a Maven Wrapper setup for Java projects using the Maven build system. The .mvn/ directory is where Maven stores configuration files for the project. It can contain settings specific to the project, such as JVM options (jvm.config) or project-level configuration.

**Comment by AlexandruIliescu** [comment]
It should be untracked, not removed. We discussed about this on the course many times.

**Comment by AlexandruIliescu** [comment]
Those files from my list should not be visible here on GitHub.

**Comment by AlexandruIliescu** [comment]
We can consider removing them from GitHub because we don't want them here. Since we already have them on the repository, we can consider that by doing the `untrack` step, those files will be removed/forgotten by GitHub.

**Comment by AlexandruIliescu** [comment]
You can use [this project ](https://github.com/FlorinGavan/TaskFlow) as an example in terms of the files that should be visible on the remote repository.

**Comment by alinaitschool** [comment]
Maven wrapper should be in git, because like that you don't need to install maven manually when you checkout the project. You can check for example this project from tomcat: https://github.com/apache/tomcat-jakartaee-migration.
Like that also everybody working on that project is using exactly the same version of maven.

**Comment by AlexandruIliescu** [comment]
The `.gitignore` file currently contains a line explicitly unignoring `!.mvn/wrapper/maven-wrapper.jar`, meaning the binary `maven-wrapper.jar` will still be committed to the repository. Committing a precompiled binary can be a security risk because it's a non-readable file that may be tampered with or contain vulnerabilities.

The main point I was raising with the issue is that it’s generally easier and safer to exclude Maven binary files (like maven-wrapper.jar) from GitHub to avoid potential security risks, rather than gaining a small convenience advantage by having Maven installed locally for everyone through the wrapper.

In a public repository, any binary file, including the Maven wrapper JAR, can potentially introduce vulnerabilities or be tampered with. By excluding these files, we reduce the attack surface and follow better security practices.

Additionally, the small advantage of automatically having Maven installed through the wrapper doesn't outweigh the potential risks in a public setting. The whole team should have a standard environment set up anyway, which includes the required Java version, Maven version, and any other dependencies. This ensures consistency across the project without exposing unnecessary files in a public repository.

Also, please note that public repositories that are meant to be used as `demonstration repositories` do not stand as overall best practices standards.  Instead, we can have a look at [OWAS Top Ten](https://owasp.org/www-project-top-ten/) documentation or any relevant material/documentation.

**Comment by alinaitschool** [comment]
@AlexandruIliescu  can you please, close the issue? Thanks.

**Comment by alinaitschool** [comment]
In fact I discover I can close by my self :))
